---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  log_file: /var/log/chef-solo.log

platforms:
- name: opscode-ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    customize:
      cpus: 2
      memory: 1024
suites:
- name: default
  run_list:
  - "recipe[rs-cookbooks_ci::default]"
  attributes: 
      rs-cookbooks_ci:
          jenkins:
              username: 'qa'
              password: 'secret11'
              user_full_name: 'White Team QA'
              user_email: 'white@rightscale.com'
              jobs:
                  marker:
                     git_repo: 'git://github.com/rightscale-cookbooks/marker.git'
                     git_branch: 'master'
              git_setup:
                  git_username: 'rightscale-cookbooks-jenkins'
                  git_email:  'cookbooks@rightscale.com'
